/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.VIEW.WorkSpace;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Dinh Khanh Du
 */
public abstract class WorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkPanel
     */
    protected DefaultTableModel tableModel = new DefaultTableModel();
    public WorkPanel() {
        initComponents();
        
        table.setModel(tableModel);
    }
    
    public void addColumns(String... columns) {
        for (String column: columns) {
            tableModel.addColumn(column);
        }
    }
    
    public void refresh() {
        tableModel.setRowCount(0);
        addRows();
    }
    
    public void addRightPanels(JPanel... items) {
        for (JPanel item: items) {
            rightPanel.add(item);
        }
    }
    
    public abstract void addRows();
    
    public abstract void insert();
    public abstract void delete();
    public abstract void update();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        btnInsert.setText("Thêm");
        jPanel4.add(btnInsert);

        btnDelete.setText("Xoá");
        jPanel4.add(btnDelete);

        btnUpdate.setText("Cập nhật");
        jPanel4.add(btnUpdate);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));

        btnRefresh.setText("Làm mới");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        rightPanel.add(btnRefresh);

        jPanel5.add(rightPanel, java.awt.BorderLayout.LINE_END);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
